auto: true

#markdown: rdiscount
#pygments: true
#paginate: 8
#permalink: /:title

title: Shayne' Blog
url: http://ShayneChow.github.com/
feed: /atom.xml
author_info: <a href="http://weibo.com/206272757">ShayneChow</a>
